/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package pl.ing.green.atmservice.api;

import pl.ing.green.atmservice.model.ATM;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import java.util.List;
import java.util.Optional;
import jakarta.annotation.Generated;
import pl.ing.green.atmservice.model.Task;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-05-10T23:05:31.627387+02:00[Europe/Warsaw]")
@Validated
@Tag(name = "atms", description = "the atms API")
public interface AtmsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /atms/calculateOrder
     * Calculates ATMs order for service team
     *
     * @param task  (required)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "calculate",
        description = "Calculates ATMs order for service team",
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ATM.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/atms/calculateOrder",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<List<ATM>> calculate(
        @Parameter(name = "Task", description = "", required = true) @Valid @RequestBody List<Task> task
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"atmId\" : 500, \"region\" : 10 }, { \"atmId\" : 500, \"region\" : 10 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
